Feature 8: User can delete their current projects (Nowwws)
AnthonyVNgo/final-project pull request #22
Opened 2022-06-27 03:53 UTC by AnthonyVNgo

![Kapture 2022-06-26 at 20 51 00](https://user-images.githubusercontent.com/99709530/175856730-cc3adc26-a59e-498a-93f0-1670eff282d0.gif)

2022-06-27 16:08 UTC, thebearingedge requested changes
Ok, please see my comments and also scan your pull request for commented lines that should be deleted.

https://github.com/AnthonyVNgo/final-project/pull/22/files

2022-06-27 16:08 UTC, thebearingedge commented on client/pages/update-my-now.jsx
>      if (!this.state.user) return <Redirect to="sign-in" />;
You can remove one of these user guards. Only the first one is happening

2022-06-27 16:08 UTC, thebearingedge commented on client/pages/update-my-now.jsx
> +  }
in your `.then()` on line 107 you need to filter your nowEntry array to exclude the deleted one and update the state to re-render the entries.

2022-06-27 16:08 UTC, thebearingedge commented on client/pages/update-my-now.jsx
> +  }
Actually, I think the main issue is that your NowEntryList component isn't pulling its weight. Just map the Now Entry list items directly in this component's render method.

2022-06-28 09:25 UTC, AnthonyVNgo commented
![Kapture 2022-06-28 at 02 19 40](https://user-images.githubusercontent.com/99709530/176144116-bf8532f2-f7c3-42d4-9c7a-a96a701fdf75.gif)

2022-06-28 18:04 UTC, AnthonyVNgo commented
![Kapture 2022-06-28 at 10 57 36](https://user-images.githubusercontent.com/99709530/176251780-ad33c55a-fd89-491d-ad05-7fc5cedef5e2.gif)

2022-06-29 06:26 UTC, merged